apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/nest-microservices-448914/notifications/production
          name: notifications
          env:
            - name: PORT
              value: '3000'
            - name: GOOGLE_OAUTH_CLIENT_ID
              value: 865801919016-8f0r8tgnolpcp7k77vvjj899dfl1vutt.apps.googleusercontent.com
            - name: SMTP_USER
              value: itadoriyuuji240@gmail.com
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google
                  key: clientSecret
            - name: GOOGLE_OAUTH_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google
                  key: refreshToken
          ports:
            - containerPort: 3000
